apiVersion: v1
kind: ConfigMap
metadata:
  name: blogginrose-service-config
  labels:
    app: blogginrose-service
data:
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_SSL_MODE: "${POSTGRES_SSL_MODE}"
  SECRETS_PATH: "/secrets"
  POSTGRES_PASSWORD_FILE: "/secrets/db-password"
  JWT_SECRET_FILE: "/secrets/jwt-secret"
  PORT: "${PORT}"
  ALLOWED_ORIGINS: "https://blogginrose.com"
  ADMIN_USERNAME: "${ADMIN_USERNAME}"
